### ISSUE TITLE
running integration tests fail with Firefox 35

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-integration-test#16]
To workaround that, 

1. Disable autoupdating in Settings->Advanced->Update
2. install Firefox 34:
https://support.mozilla.org/en-US/kb/install-older-version-of-firefox?redirectlocale=en-US&redirectslug=Installing+a+previous+version+of+Firefox

Related issue: https://github.com/theintern/intern/issues/333

**Comment by janl** [comment]
can we pin FF on Travis?

**Comment by boennemann** [comment]
pinning FF on Travis requires configuration in every single .travis.yml :/ http://docs.travis-ci.com/user/firefox/

**Comment by gr2m** [comment]
I think the don't have FF 35 on Travis yet, the tests were still running, just failing. Let's get back to this after conc.at, I'd say

**Comment by janl** [comment]
@boennemann can’t we use our dotfile-distribution feature for that?

**Comment by boennemann** [comment]
https://github.com/theintern/intern/issues/333 closes this
